name: iCleanerLite
options:
  deploymentTarget:
    iOS: "17.0"
  bundleIdPrefix: com.mobiminer115
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  iCleanerLite:
    type: application
    platform: iOS
    sources:
      - path: iCleanerLite
    info:
      path: iCleanerLite/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mobiminer115.iCleanerLite
        PRODUCT_NAME: iCleanerLite
        INFOPLIST_FILE: iCleanerLite/Info.plist
        SWIFT_VERSION: 5.0
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
